apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngc-monkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngc-monkey
  template:
    metadata:
      labels:
        app: ngc-monkey
    spec:
      containers:
        - name: server
          image: gcr.io/redis-dev-next-gen-cluster/ngc-monkey-server
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ngc-monkey
spec:
  selector:
    app: ngc-monkey
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP